{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/2.0.0-SNAPSHOT/runtime-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "runtime",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-watchosarm32-2.0.0-SNAPSHOT.klib",
          "size": 49409,
          "sha512": "80da867dae9c892e1c22158e1346627662dd41b3b35490b88f7cba14f408f80b04c28d54e3952b0f85da6913a542e8854f0f93eb7173ecc6f156ecc4f935d00d",
          "sha256": "0a3206e3b7bba077efafe4d7a52fcda3656b42a1bf4320164464fbc74ce9cc54",
          "sha1": "f145d1c601ed1baac33444b1aa0f566690e8973b",
          "md5": "e82eaf85bd94914d6771c28fdded206b"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-watchosarm32-2.0.0-SNAPSHOT-metadata.jar",
          "url": "runtime-watchosarm32-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1d8527a2fb9344e6a22168c4e7689cfc27e74b7fba240f589aad1e525083e4ce4058efa4eeb700fb0e194ed669d29749642cb8acbc9700fd9da6e4786571a98f",
          "sha256": "0067355b66adf1f10270b666c1c4ab0756b54741118a16f24e956db0ac292b96",
          "sha1": "2f90a7d4a8aaaa1d0cc269108444b633fdb9daf0",
          "md5": "00c637356359413993cf9c6a12ee4683"
        }
      ]
    }
  ]
}
