CREATE TABLE foo(
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL
);

SELECT * INTO :foo, :bar FROM foo;

SET :foo = 42;

-- SET :foo = WITH w AS (SELECT name AS n FROM foo) SELECT n FROM w;
SET :foo = SELECT name FROM foo;
SET :foo = SELECT name AS n FROM foo;
