{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/2.0.0-SNAPSHOT/runtime-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "runtime",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-watchosx64-2.0.0-SNAPSHOT.klib",
          "size": 49392,
          "sha512": "a3ffe1d7373dfc7ff6b3f3bd447b70204eaf2bd02a87274cd13f6e108c44633a2e49832daa986140b71b3535db28ebcb47d387c1a56167ec56c951b98cd3f5e0",
          "sha256": "61b39dde8bac505d4bc875e213a73bf27505cbbcb2937678776443aab41f9a7b",
          "sha1": "7a89f21fbdfe71dc57e9238b3903cc77051a859d",
          "md5": "47d61c4be2000ea7c9bfe405f939759d"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-watchosx64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "runtime-watchosx64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4a76b006e6134813100a9679cb2a8028135969ddf06ec506e06ce1a1e712db75abbaf93fb89c05e3caaf49b8e8a2752b8bccf25535fe8873dbb76d884b763a35",
          "sha256": "9e858605d076c41e6fa8bb641a9d023c1f9bc922ae3ad406a39520bd38b79950",
          "sha1": "c3a7a8c4a1b66c38a7de1e2bfc4db44e43c63f94",
          "md5": "392aecc4c9f65c73559e08fff7205400"
        }
      ]
    }
  ]
}
