{
  "formatVersion": "1.1",
  "component": {
    "url": "../../native-driver/2.0.0-SNAPSHOT/native-driver-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "native-driver",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "sqliter-driver",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-driver.klib",
          "url": "native-driver-watchossimulatorarm64-2.0.0-SNAPSHOT.klib",
          "size": 46812,
          "sha512": "30d27f82044f9b87bf2d8fb73608500a12605a5ff4fd5db8322aa057f084ada79a42a2a556ddadde371a3e98123e844c47a1ee96bb4e65ffae3b6ed359cfa9f8",
          "sha256": "86eab8f4526649d70d8159471db6e2b0daf83f1bcf815cb0b1862b49007b3054",
          "sha1": "9d219377ccde6ff072832ce11514a3b3c29dc54a",
          "md5": "bca1978f63b372b17891dd93de34892a"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "sqliter-driver",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-driver-watchossimulatorarm64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "native-driver-watchossimulatorarm64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 6008,
          "sha512": "dce9ce442079930a6080082324979eb22c7001875f5dd9acee6ce3047b6ae41241f8dae88b23bc3583dd5d13ef7e35357ba597a14a73da7f860e07131c3a9773",
          "sha256": "5f46ca055411bf54f4954cd75fbd03009152ecdec5fbb7096a7660cf0d1489b8",
          "sha1": "357a3da420e4284d52b8a08ed91966916645dbc7",
          "md5": "68081c57c6c0d0b5f7c1848e8c5a85fa"
        }
      ]
    }
  ]
}
