{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/2.0.0-SNAPSHOT/runtime-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "runtime",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-watchosx86-2.0.0-SNAPSHOT.klib",
          "size": 49392,
          "sha512": "ae4c6f436845454e6aeb455d09fb0d3744fc2e8b588eefc246178da3b7ce8278632c5f649deb8fa96bdb76691ff87f5abc8040660095bbcfcfdb937d0c59df5d",
          "sha256": "f952867fc4bfb661250d9183d142b8a3e2fa80c9effbbf12385b237710f2aaf3",
          "sha1": "b7f19c4b62abc3e49b66732aca2dc769e2972e64",
          "md5": "1138188910922e72bfc9611aac5ee70d"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-watchosx86-2.0.0-SNAPSHOT-metadata.jar",
          "url": "runtime-watchosx86-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4989be41c0d271591d6f22da6af84eabe2a864dc2fffcc1a2f580174f36fd6b2b7e92f2ba200b85f7ec716f572fa0257d16c952b44f794338f7afb03066d0609",
          "sha256": "b590b20050ea1dc0fa61252b905c135b096e955d423c8f08ae26eb1b5fe762be",
          "sha1": "1a965162ca4283d417231f48e5010cd7fe210429",
          "md5": "c78aa62f132877c3f0e69f18645f5985"
        }
      ]
    }
  ]
}
