{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "primitive-adapters",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqldelight-primitive-adapters-metadata-2.0.0-SNAPSHOT.jar",
          "url": "primitive-adapters-2.0.0-SNAPSHOT.jar",
          "size": 4613,
          "sha512": "759f3d915f1553cb3d79d2af38d53d295890f6eac96e470280cece44097afb4c4c2c31c3a7449895475ee2d8f41281693da9d9a924eb08015d71978e0943d0db",
          "sha256": "c76254d8c2f30f62d76413b25e4576613325cc660392e30ce0e67d4c577c1808",
          "sha1": "93c80d9d065fadfa48b9881c48652362bf6b2ea5",
          "md5": "26f763485b3edaabbff4b113dda8d4f6"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-iosarm32/2.0.0-SNAPSHOT/primitive-adapters-iosarm32-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-iosarm32",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-iosarm32/2.0.0-SNAPSHOT/primitive-adapters-iosarm32-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-iosarm32",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-iosarm64/2.0.0-SNAPSHOT/primitive-adapters-iosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-iosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-iosarm64/2.0.0-SNAPSHOT/primitive-adapters-iosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-iosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-iossimulatorarm64/2.0.0-SNAPSHOT/primitive-adapters-iossimulatorarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-iossimulatorarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-iossimulatorarm64/2.0.0-SNAPSHOT/primitive-adapters-iossimulatorarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-iossimulatorarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-iosx64/2.0.0-SNAPSHOT/primitive-adapters-iosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-iosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-iosx64/2.0.0-SNAPSHOT/primitive-adapters-iosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-iosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../primitive-adapters-js/2.0.0-SNAPSHOT/primitive-adapters-js-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-js",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../primitive-adapters-js/2.0.0-SNAPSHOT/primitive-adapters-js-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-js",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../primitive-adapters-js/2.0.0-SNAPSHOT/primitive-adapters-js-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-js",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../primitive-adapters-js/2.0.0-SNAPSHOT/primitive-adapters-js-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-js",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../primitive-adapters-jvm/2.0.0-SNAPSHOT/primitive-adapters-jvm-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-jvm",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../primitive-adapters-jvm/2.0.0-SNAPSHOT/primitive-adapters-jvm-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-jvm",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-linuxx64/2.0.0-SNAPSHOT/primitive-adapters-linuxx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-linuxx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-macosarm64/2.0.0-SNAPSHOT/primitive-adapters-macosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-macosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-macosarm64/2.0.0-SNAPSHOT/primitive-adapters-macosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-macosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-macosx64/2.0.0-SNAPSHOT/primitive-adapters-macosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-macosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-macosx64/2.0.0-SNAPSHOT/primitive-adapters-macosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-macosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-mingwx64/2.0.0-SNAPSHOT/primitive-adapters-mingwx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-mingwx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "mingwX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-mingwx86/2.0.0-SNAPSHOT/primitive-adapters-mingwx86-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-mingwx86",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-tvosarm64/2.0.0-SNAPSHOT/primitive-adapters-tvosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-tvosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-tvosarm64/2.0.0-SNAPSHOT/primitive-adapters-tvosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-tvosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-tvossimulatorarm64/2.0.0-SNAPSHOT/primitive-adapters-tvossimulatorarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-tvossimulatorarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-tvossimulatorarm64/2.0.0-SNAPSHOT/primitive-adapters-tvossimulatorarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-tvossimulatorarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-tvosx64/2.0.0-SNAPSHOT/primitive-adapters-tvosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-tvosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-tvosx64/2.0.0-SNAPSHOT/primitive-adapters-tvosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-tvosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-watchosarm32/2.0.0-SNAPSHOT/primitive-adapters-watchosarm32-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-watchosarm32",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-watchosarm32/2.0.0-SNAPSHOT/primitive-adapters-watchosarm32-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-watchosarm32",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-watchosarm64/2.0.0-SNAPSHOT/primitive-adapters-watchosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-watchosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-watchosarm64/2.0.0-SNAPSHOT/primitive-adapters-watchosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-watchosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-watchossimulatorarm64/2.0.0-SNAPSHOT/primitive-adapters-watchossimulatorarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-watchossimulatorarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-watchossimulatorarm64/2.0.0-SNAPSHOT/primitive-adapters-watchossimulatorarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-watchossimulatorarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-watchosx64/2.0.0-SNAPSHOT/primitive-adapters-watchosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-watchosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-watchosx64/2.0.0-SNAPSHOT/primitive-adapters-watchosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-watchosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-watchosx86/2.0.0-SNAPSHOT/primitive-adapters-watchosx86-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-watchosx86",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../primitive-adapters-watchosx86/2.0.0-SNAPSHOT/primitive-adapters-watchosx86-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "primitive-adapters-watchosx86",
        "version": "2.0.0-SNAPSHOT"
      }
    }
  ]
}
