{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "postgresql-dialect",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.4.1"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "postgresql-dialect-2.0.0-SNAPSHOT.jar",
          "url": "postgresql-dialect-2.0.0-SNAPSHOT.jar",
          "size": 1239623,
          "sha512": "d60faf0fba1c74859b30b4a931f65f2a2c9dd1893830d4dee7bc0ada8e3ed8adc5d647d2470e2db1e15f28a4b7a0382130ec6f114a23b6dd86a69699feeac40b",
          "sha256": "4fdb3afcc41a8554929ff4488e3470953f6de7eecf54294075ca1e864a865be8",
          "sha1": "20999d417f41544e08e7b709d8aeea470a3e7810",
          "md5": "f0492f690f55ec1e845b869af929ffa9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.4.1"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "postgresql-dialect-2.0.0-SNAPSHOT.jar",
          "url": "postgresql-dialect-2.0.0-SNAPSHOT.jar",
          "size": 1239623,
          "sha512": "d60faf0fba1c74859b30b4a931f65f2a2c9dd1893830d4dee7bc0ada8e3ed8adc5d647d2470e2db1e15f28a4b7a0382130ec6f114a23b6dd86a69699feeac40b",
          "sha256": "4fdb3afcc41a8554929ff4488e3470953f6de7eecf54294075ca1e864a865be8",
          "sha1": "20999d417f41544e08e7b709d8aeea470a3e7810",
          "md5": "f0492f690f55ec1e845b869af929ffa9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "postgresql-dialect-2.0.0-SNAPSHOT.jar",
          "url": "postgresql-dialect-2.0.0-SNAPSHOT.jar",
          "size": 1239623,
          "sha512": "d60faf0fba1c74859b30b4a931f65f2a2c9dd1893830d4dee7bc0ada8e3ed8adc5d647d2470e2db1e15f28a4b7a0382130ec6f114a23b6dd86a69699feeac40b",
          "sha256": "4fdb3afcc41a8554929ff4488e3470953f6de7eecf54294075ca1e864a865be8",
          "sha1": "20999d417f41544e08e7b709d8aeea470a3e7810",
          "md5": "f0492f690f55ec1e845b869af929ffa9"
        }
      ]
    }
  ]
}
