{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "coroutines-extensions",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "app.cash.sqldelight",
          "module": "async-extensions",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "sqldelight-coroutines-extensions-metadata-2.0.0-SNAPSHOT.jar",
          "url": "coroutines-extensions-2.0.0-SNAPSHOT.jar",
          "size": 4231,
          "sha512": "6f869de137ae13beaca8e842704b4f397b6492c3aa4b9e315993ee02bf92cadd9debf0b5f536eb0213ddbfb88b63d90b6233403bd989d1ef69da788249aee412",
          "sha256": "e1669a579fbaa26a9acbf6c803a1711eaa6342c86c39a2cc6c49fb22be57aeb6",
          "sha1": "be3169edd6389982af2c5c71e0878b8fd9154699",
          "md5": "918aa6bfa7b7b42315d5d1204c4e803a"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-iosarm32/2.0.0-SNAPSHOT/coroutines-extensions-iosarm32-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-iosarm32",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-iosarm32/2.0.0-SNAPSHOT/coroutines-extensions-iosarm32-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-iosarm32",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-iosarm64/2.0.0-SNAPSHOT/coroutines-extensions-iosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-iosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-iosarm64/2.0.0-SNAPSHOT/coroutines-extensions-iosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-iosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-iossimulatorarm64/2.0.0-SNAPSHOT/coroutines-extensions-iossimulatorarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-iossimulatorarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-iossimulatorarm64/2.0.0-SNAPSHOT/coroutines-extensions-iossimulatorarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-iossimulatorarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-iosx64/2.0.0-SNAPSHOT/coroutines-extensions-iosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-iosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-iosx64/2.0.0-SNAPSHOT/coroutines-extensions-iosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-iosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coroutines-extensions-js/2.0.0-SNAPSHOT/coroutines-extensions-js-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-js",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coroutines-extensions-js/2.0.0-SNAPSHOT/coroutines-extensions-js-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-js",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coroutines-extensions-js/2.0.0-SNAPSHOT/coroutines-extensions-js-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-js",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../coroutines-extensions-js/2.0.0-SNAPSHOT/coroutines-extensions-js-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-js",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coroutines-extensions-jvm/2.0.0-SNAPSHOT/coroutines-extensions-jvm-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-jvm",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../coroutines-extensions-jvm/2.0.0-SNAPSHOT/coroutines-extensions-jvm-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-jvm",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-linuxx64/2.0.0-SNAPSHOT/coroutines-extensions-linuxx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-linuxx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-macosarm64/2.0.0-SNAPSHOT/coroutines-extensions-macosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-macosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-macosarm64/2.0.0-SNAPSHOT/coroutines-extensions-macosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-macosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-macosx64/2.0.0-SNAPSHOT/coroutines-extensions-macosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-macosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-macosx64/2.0.0-SNAPSHOT/coroutines-extensions-macosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-macosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-mingwx64/2.0.0-SNAPSHOT/coroutines-extensions-mingwx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-mingwx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-tvosarm64/2.0.0-SNAPSHOT/coroutines-extensions-tvosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-tvosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-tvosarm64/2.0.0-SNAPSHOT/coroutines-extensions-tvosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-tvosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-tvossimulatorarm64/2.0.0-SNAPSHOT/coroutines-extensions-tvossimulatorarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-tvossimulatorarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-tvossimulatorarm64/2.0.0-SNAPSHOT/coroutines-extensions-tvossimulatorarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-tvossimulatorarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-tvosx64/2.0.0-SNAPSHOT/coroutines-extensions-tvosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-tvosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-tvosx64/2.0.0-SNAPSHOT/coroutines-extensions-tvosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-tvosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchosarm32/2.0.0-SNAPSHOT/coroutines-extensions-watchosarm32-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-watchosarm32",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchosarm32/2.0.0-SNAPSHOT/coroutines-extensions-watchosarm32-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-watchosarm32",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchosarm64/2.0.0-SNAPSHOT/coroutines-extensions-watchosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-watchosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchosarm64/2.0.0-SNAPSHOT/coroutines-extensions-watchosarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-watchosarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchossimulatorarm64/2.0.0-SNAPSHOT/coroutines-extensions-watchossimulatorarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-watchossimulatorarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchossimulatorarm64/2.0.0-SNAPSHOT/coroutines-extensions-watchossimulatorarm64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-watchossimulatorarm64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchosx64/2.0.0-SNAPSHOT/coroutines-extensions-watchosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-watchosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchosx64/2.0.0-SNAPSHOT/coroutines-extensions-watchosx64-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-watchosx64",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchosx86/2.0.0-SNAPSHOT/coroutines-extensions-watchosx86-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-watchosx86",
        "version": "2.0.0-SNAPSHOT"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../coroutines-extensions-watchosx86/2.0.0-SNAPSHOT/coroutines-extensions-watchosx86-2.0.0-SNAPSHOT.module",
        "group": "app.cash.sqldelight",
        "module": "coroutines-extensions-watchosx86",
        "version": "2.0.0-SNAPSHOT"
      }
    }
  ]
}
