{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/2.0.0-SNAPSHOT/runtime-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "runtime",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-iosarm32-2.0.0-SNAPSHOT.klib",
          "size": 49374,
          "sha512": "7b2fa934154e5c5af9026464458e84283c3dce2795b0374acbcf78b5e74dcaefc48e09b51500e7fb8a16c82665e68670702b7bcb6b90acb6b1454bfd81dea908",
          "sha256": "0e629e6f0a1173e695a8ac5fcd6996a9399d11b5d5ded1dfbadcb07c5ef5d9d2",
          "sha1": "5cdceaa356d697319ec19667b96bb165b33b3a50",
          "md5": "48efadef0113e9d7895f3fd5c128a749"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-iosarm32-2.0.0-SNAPSHOT-metadata.jar",
          "url": "runtime-iosarm32-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "67a94f660d856e0975e2f68a7316986078b50912dea76084d97c738ce334cd93ea2f82d772f08a0696a4d8f898d80500a8f901ac921ac315020bec680fbd8a1d",
          "sha256": "517dc39407ce343a6f271512bfff7925cfdafbc7a773a083d4e9d7d0f31ca330",
          "sha1": "b2063d30c3dc8188685b0d46c0852c8ad81f3e4b",
          "md5": "3a013dc7017e41a32205d08421989097"
        }
      ]
    }
  ]
}
