{
  "formatVersion": "1.1",
  "component": {
    "url": "../../primitive-adapters/2.0.0-SNAPSHOT/primitive-adapters-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "primitive-adapters",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "primitive-adapters.klib",
          "url": "primitive-adapters-iosarm64-2.0.0-SNAPSHOT.klib",
          "size": 7410,
          "sha512": "ce755330a1b53e8540a4b9f8b8863f869da8d005adba858d53fa59a0aa98ae4e471a90cf475cad62ef14060ada24abb189c57f8f62fe8a688fc07a6f4b1abf18",
          "sha256": "72f176423dee0df025d8673f3322d1b3d940346440423e277c04c1e056a34531",
          "sha1": "89f849af5054dc9d198108187f340fc0eb299606",
          "md5": "e4efc82c1d87dad6964d6bd75b55ef7b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqldelight-primitive-adapters-iosarm64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "primitive-adapters-iosarm64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e98abd2c104bbfd10b3cb3c7545993db72cb5928ba8db8a73e78a09fd3a58c73bbb0ec2985804435c4a3a2e3dcab6dadb60a27257bfa8ef4ecf036446a48bac7",
          "sha256": "0ffd964b4aee7d7e2ee7777ee6e353f616514207055ca5a14f7e9e749c88f3d8",
          "sha1": "b7ccbb9abd5905bff6f27717e41f358354fbb972",
          "md5": "7e47fb3a9b42930b21a6a8dd4c21ed05"
        }
      ]
    }
  ]
}
