{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "rxjava3-extensions",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "rxjava3-extensions-2.0.0-SNAPSHOT.jar",
          "url": "rxjava3-extensions-2.0.0-SNAPSHOT.jar",
          "size": 5937,
          "sha512": "a8690dbe95f331435c95c4da54b693d9a2d675a0fd77785c45917f578d095970ab273aeeae5259cca437d3ff2047d23ed683243a11761997fcd642df6dc46312",
          "sha256": "99eeeece36baccca1123cfcbcaa4dc0a65ae7a48b38a96c6e348663517274e90",
          "sha1": "64baea54132e6cb9e37f4c7bfe6537577094d8fd",
          "md5": "19f8d79c55ca413a040228fd379d9289"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.5"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "rxjava3-extensions-2.0.0-SNAPSHOT.jar",
          "url": "rxjava3-extensions-2.0.0-SNAPSHOT.jar",
          "size": 5937,
          "sha512": "a8690dbe95f331435c95c4da54b693d9a2d675a0fd77785c45917f578d095970ab273aeeae5259cca437d3ff2047d23ed683243a11761997fcd642df6dc46312",
          "sha256": "99eeeece36baccca1123cfcbcaa4dc0a65ae7a48b38a96c6e348663517274e90",
          "sha1": "64baea54132e6cb9e37f4c7bfe6537577094d8fd",
          "md5": "19f8d79c55ca413a040228fd379d9289"
        }
      ]
    }
  ]
}
