{
  "formatVersion": "1.1",
  "component": {
    "url": "../../native-driver/2.0.0-SNAPSHOT/native-driver-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "native-driver",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "sqliter-driver",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-driver.klib",
          "url": "native-driver-watchosarm64-2.0.0-SNAPSHOT.klib",
          "size": 46725,
          "sha512": "194185fce838bea9e337844bb88df80d8a8e9cb0d95db15404579b0848e6d040c749a3f53b729889a5ff62d1c54d3c330c025ecfc02dfb79b31aabf2e6d6f962",
          "sha256": "731c18e3ef819719db781efe2cc881c39b91e6cca9c0e7cc3f5c16fdaf28de81",
          "sha1": "94dce563c50d372bec9ec73a2a11f32e51fa0675",
          "md5": "f9a84a060d74a4ca6de17d1485e6ec51"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "sqliter-driver",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-driver-watchosarm64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "native-driver-watchosarm64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 6008,
          "sha512": "dce9ce442079930a6080082324979eb22c7001875f5dd9acee6ce3047b6ae41241f8dae88b23bc3583dd5d13ef7e35357ba597a14a73da7f860e07131c3a9773",
          "sha256": "5f46ca055411bf54f4954cd75fbd03009152ecdec5fbb7096a7660cf0d1489b8",
          "sha1": "357a3da420e4284d52b8a08ed91966916645dbc7",
          "md5": "68081c57c6c0d0b5f7c1848e8c5a85fa"
        }
      ]
    }
  ]
}
