{
  "formatVersion": "1.1",
  "component": {
    "url": "../../native-driver/2.0.0-SNAPSHOT/native-driver-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "native-driver",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "sqliter-driver",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-driver.klib",
          "url": "native-driver-macosarm64-2.0.0-SNAPSHOT.klib",
          "size": 46758,
          "sha512": "f1c661c3a2ec0ee76875fa3fd8536d4f6efd44399a44aa2d2a2545160d50eae78a66ecb634aab74d46fd964697abaf3f6d445a11217dbf80dc5439aa0d021b57",
          "sha256": "ce5186a42aee09e9297b5c323942fa90404ffd7036c57835acfa905b4439880e",
          "sha1": "b6378f8a7a9445c65566ff0d5ad72d9bfd1fe342",
          "md5": "93c5e76e272839c68caf93b31c76e373"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "sqliter-driver",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-driver-macosarm64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "native-driver-macosarm64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 6008,
          "sha512": "b1ebd97feb4f0b066cbc33c75ad0108cd1c04285d5e323481d279f6c3304cba3ecc036258b89da423736f7c81c22bfaa45f74ff2c8a4060370672ac640297967",
          "sha256": "074c7f86c8e7f58e109d2e04563619ca553a053bfe40113e4d6ce054947371cb",
          "sha1": "2e45db9d3ef42d34efff9a28f1a57c0bf2aa4774",
          "md5": "20f8bb7f5976166326383abe46c79e91"
        }
      ]
    }
  ]
}
