{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "sqlite-3-38-dialect",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-35-dialect",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-38-dialect-2.0.0-SNAPSHOT.jar",
          "url": "sqlite-3-38-dialect-2.0.0-SNAPSHOT.jar",
          "size": 245473,
          "sha512": "6b5a388c712c5cc4149114ccfa36468ea79e512bf4a02a1caa8cdae483cde31fe512896d8aacb76a0959fd8280f51cf693340930c5bb0bfb19913a41318ff7ae",
          "sha256": "f975c6aa73fc8110ed5b5afe8cae479e6adc3df3e0946a0ad5589fc81159c50a",
          "sha1": "2b7476468906608ebfc64f3f840a7bc52f2e2c6a",
          "md5": "1313024928b802ea014417afcb613c90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-35-dialect",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-38-dialect-2.0.0-SNAPSHOT.jar",
          "url": "sqlite-3-38-dialect-2.0.0-SNAPSHOT.jar",
          "size": 245473,
          "sha512": "6b5a388c712c5cc4149114ccfa36468ea79e512bf4a02a1caa8cdae483cde31fe512896d8aacb76a0959fd8280f51cf693340930c5bb0bfb19913a41318ff7ae",
          "sha256": "f975c6aa73fc8110ed5b5afe8cae479e6adc3df3e0946a0ad5589fc81159c50a",
          "sha1": "2b7476468906608ebfc64f3f840a7bc52f2e2c6a",
          "md5": "1313024928b802ea014417afcb613c90"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite-3-38-dialect-2.0.0-SNAPSHOT.jar",
          "url": "sqlite-3-38-dialect-2.0.0-SNAPSHOT.jar",
          "size": 245473,
          "sha512": "6b5a388c712c5cc4149114ccfa36468ea79e512bf4a02a1caa8cdae483cde31fe512896d8aacb76a0959fd8280f51cf693340930c5bb0bfb19913a41318ff7ae",
          "sha256": "f975c6aa73fc8110ed5b5afe8cae479e6adc3df3e0946a0ad5589fc81159c50a",
          "sha1": "2b7476468906608ebfc64f3f840a7bc52f2e2c6a",
          "md5": "1313024928b802ea014417afcb613c90"
        }
      ]
    }
  ]
}
