package app.softwork.sqldelight.db2dialect.grammar.mixins

import com.alecstrong.sql.psi.core.psi.impl.SqlColumnDefImpl
import com.intellij.lang.ASTNode

internal class ColumnDefMixin(node: ASTNode) : SqlColumnDefImpl(node) {

  override fun hasDefaultValue(): Boolean {
    return columnConstraintList.any { "GENERATED BY DEFAULT" in it.node.text  } || super.hasDefaultValue()
  }
}
