{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/2.0.0-SNAPSHOT/runtime-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "runtime",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-watchossimulatorarm64-2.0.0-SNAPSHOT.klib",
          "size": 49495,
          "sha512": "7e6beee9e42b7ca7ffa6a1252d6c134636d3922b7e152a28becaeba11893d1d573713886b95a65ce4ea1e14b0916f305b0ee9f1bd8503affa848153a85e02185",
          "sha256": "f0d9bcfb74305e98320e563a23fe0159c7db36837bb6751b6d4ffb42958e8840",
          "sha1": "539d00ca9313769d09e92d21509529f874df4191",
          "md5": "319ca58c90e8da4fc54214ed27aafed0"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-watchossimulatorarm64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "runtime-watchossimulatorarm64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e2fd5cbc9dacad7780ba94a81c9a5d1d3c323f9defbfaa315e6650fdc92d70887fb4bf621557f7eb4cd62059e95f9a455891f562b4967f1fb1c8ef24abd9be44",
          "sha256": "8f09346eb3206ec40c7568cfeb7aa8efb14bd487ae3b6455b6c838394f5e2065",
          "sha1": "3932308ccfd67b608b1f65ed94e04728b9214250",
          "md5": "ca591f7d5ed20f40d3ad84563ddf3511"
        }
      ]
    }
  ]
}
