{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "sqlite-3-18-dialect",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-18-dialect-2.0.0-SNAPSHOT.jar",
          "url": "sqlite-3-18-dialect-2.0.0-SNAPSHOT.jar",
          "size": 69238,
          "sha512": "f5999f1c3e0288f5c63239a9a44e5eaf4c6d41b7c8623232c26e5f4ef77c8bc11a20d5cae3ee5315270df7e1e721594fe13e915a4412a0042913dca594cf5058",
          "sha256": "9151ac50cdd53fd5d11c36d368cf14f56085d58ba3e452bb96169f99ffa31726",
          "sha1": "ee9b540a18a048450d197f079eed740bb9ec6fd2",
          "md5": "638eacbb0f34ca78d2ee4b344eb0318a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-18-dialect-2.0.0-SNAPSHOT.jar",
          "url": "sqlite-3-18-dialect-2.0.0-SNAPSHOT.jar",
          "size": 69238,
          "sha512": "f5999f1c3e0288f5c63239a9a44e5eaf4c6d41b7c8623232c26e5f4ef77c8bc11a20d5cae3ee5315270df7e1e721594fe13e915a4412a0042913dca594cf5058",
          "sha256": "9151ac50cdd53fd5d11c36d368cf14f56085d58ba3e452bb96169f99ffa31726",
          "sha1": "ee9b540a18a048450d197f079eed740bb9ec6fd2",
          "md5": "638eacbb0f34ca78d2ee4b344eb0318a"
        }
      ]
    }
  ]
}
