{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "sqlite-3-30-dialect",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-25-dialect",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-30-dialect-2.0.0-SNAPSHOT.jar",
          "url": "sqlite-3-30-dialect-2.0.0-SNAPSHOT.jar",
          "size": 162753,
          "sha512": "bcf9c1ad93013457fc4b1aead5748901457c8e8a4223d6d853a25cfca29058e40e478d6b16cd082b7be5dd405ff8560f0f05d52919ff0e11ad3c09027513ffe6",
          "sha256": "08513cb518cbc070aed8beba33c118f87f21293f22a2af5d1d9843189c78cb5e",
          "sha1": "c15c7032b9fe5a6d7e2e61c9545f3a16011f0d92",
          "md5": "297581ce7282f8ac291d6bea7e518e7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "sqlite-3-25-dialect",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-3-30-dialect-2.0.0-SNAPSHOT.jar",
          "url": "sqlite-3-30-dialect-2.0.0-SNAPSHOT.jar",
          "size": 162753,
          "sha512": "bcf9c1ad93013457fc4b1aead5748901457c8e8a4223d6d853a25cfca29058e40e478d6b16cd082b7be5dd405ff8560f0f05d52919ff0e11ad3c09027513ffe6",
          "sha256": "08513cb518cbc070aed8beba33c118f87f21293f22a2af5d1d9843189c78cb5e",
          "sha1": "c15c7032b9fe5a6d7e2e61c9545f3a16011f0d92",
          "md5": "297581ce7282f8ac291d6bea7e518e7e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqlite-3-30-dialect-2.0.0-SNAPSHOT.jar",
          "url": "sqlite-3-30-dialect-2.0.0-SNAPSHOT.jar",
          "size": 162753,
          "sha512": "bcf9c1ad93013457fc4b1aead5748901457c8e8a4223d6d853a25cfca29058e40e478d6b16cd082b7be5dd405ff8560f0f05d52919ff0e11ad3c09027513ffe6",
          "sha256": "08513cb518cbc070aed8beba33c118f87f21293f22a2af5d1d9843189c78cb5e",
          "sha1": "c15c7032b9fe5a6d7e2e61c9545f3a16011f0d92",
          "md5": "297581ce7282f8ac291d6bea7e518e7e"
        }
      ]
    }
  ]
}
