{
  "formatVersion": "1.1",
  "component": {
    "url": "../../native-driver/2.0.0-SNAPSHOT/native-driver-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "native-driver",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "sqliter-driver",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-driver.klib",
          "url": "native-driver-tvossimulatorarm64-2.0.0-SNAPSHOT.klib",
          "size": 46786,
          "sha512": "fa9989d01ce0735ab717d8a9e3ed02e556c0676cc97e7b29799e303e99c3c5f6a2b09c81dfe35015040d1c3e8569c0c7b12b97909a07e722255d4c8a5ffa22cf",
          "sha256": "ca69b4a3931f6c9ad88796dc61ae1aa4004afb0008998369dec6b95be955cab3",
          "sha1": "ef1ee83cb3ab06a335f89c3e7f36a9b175f644cb",
          "md5": "4f9c8569c950a4211ae5714f374a47b8"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "sqliter-driver",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-driver-tvossimulatorarm64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "native-driver-tvossimulatorarm64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 6008,
          "sha512": "88125069dc3c984132f0c60c2681e57ba7abde8a2a0e63bd6098b5cea4394a14314e1591965740e3193b68afd1ed1510e0c2de2231d9bcd77f16f3a6715d765b",
          "sha256": "bbd8780d82219afb29c3af4ed45e79b61d97a5548d495608cf7d6dbcc3db712d",
          "sha1": "36de3a82826714aea90726713edbf2047e5d0bb4",
          "md5": "13b0bc15a39c4f5b44a073b60a0c5616"
        }
      ]
    }
  ]
}
