{
  "formatVersion": "1.1",
  "component": {
    "url": "../../coroutines-extensions/2.0.0-SNAPSHOT/coroutines-extensions-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "coroutines-extensions",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "async-extensions",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "coroutines-extensions.klib",
          "url": "coroutines-extensions-iosx64-2.0.0-SNAPSHOT.klib",
          "size": 10720,
          "sha512": "25eb2a3833304e6298e5a593972f976398ba7f172be372afbe2a6f58e88ac04d5daad9dc92c2392d4752b5c119dc015ee421430c91b2fc58000d7e0241ebef24",
          "sha256": "5c4236da0761a62c276fda9742082d1065ba91f9fff1e0d699b76430c2187a9b",
          "sha1": "99f458c54f5b5a7cd81f834046ab0bd7635b25f1",
          "md5": "5514bf46ac81844b7d5b8205f2a6aa75"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "async-extensions",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqldelight-coroutines-extensions-iosx64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "coroutines-extensions-iosx64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "b3cfc0074690cc5e734d09020866c18872031d1924e4c8db7e8373b77b2a9319bef98883e8050995c07bf4986599e1796846329bf6979d26b90d4bd0559b8b51",
          "sha256": "60a37d158f05a30d8008307f3f07c7f688e8efa3149a6f2f01da71716f49051f",
          "sha1": "a3a7b4e5acba3292e22aacec5b3b09fd29dbf539",
          "md5": "88fcdc5aff3743f1218fa16836c70c9c"
        }
      ]
    }
  ]
}
