{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "migrations",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "migrations-2.0.0-SNAPSHOT.jar",
          "url": "migrations-2.0.0-SNAPSHOT.jar",
          "size": 18508,
          "sha512": "e2d032f9a6fb92e1aeac1ee83ddf82bec41cd5516e9902ba7ab74c5c0fa57a6f7f3ca092e19891d6387cdfce7cb8a98699665aae2ec04b78fb1499c43a4885a6",
          "sha256": "f7c1f2d88382c4887fdf4190642cac657d72f22f59f81ac0dc8b372d6e8b69d6",
          "sha1": "f1677d558487e344392ec3bacb02b756b6c6d6e2",
          "md5": "099f1976c6ca5b4a2e1645a2bcdeab75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.alecstrong.sql.psi",
          "module": "core",
          "version": {
            "requires": "0.5.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "migrations-2.0.0-SNAPSHOT.jar",
          "url": "migrations-2.0.0-SNAPSHOT.jar",
          "size": 18508,
          "sha512": "e2d032f9a6fb92e1aeac1ee83ddf82bec41cd5516e9902ba7ab74c5c0fa57a6f7f3ca092e19891d6387cdfce7cb8a98699665aae2ec04b78fb1499c43a4885a6",
          "sha256": "f7c1f2d88382c4887fdf4190642cac657d72f22f59f81ac0dc8b372d6e8b69d6",
          "sha1": "f1677d558487e344392ec3bacb02b756b6c6d6e2",
          "md5": "099f1976c6ca5b4a2e1645a2bcdeab75"
        }
      ]
    }
  ]
}
