{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/2.0.0-SNAPSHOT/runtime-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "runtime",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-jslegacy-2.0.0-SNAPSHOT.jar",
          "url": "runtime-js-2.0.0-SNAPSHOT.jar",
          "size": 85005,
          "sha512": "7017d377892c3b04cc9175adbda39ac7f690aa2ce4e3f13e6a26fbb037b5c73d9c75adba062d8cbcba14ee37523067a053948fc57af59f11462cd27d4c49a366",
          "sha256": "7e912ae25d99e15e52a12d05307184b66807c9a55a8ca624dbfcddffda0f53a8",
          "sha1": "3509effbd75d7ec1e7f8b5f3248258822b60ae13",
          "md5": "e6e6309230b2bb35bf8dba3594968da2"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-jslegacy-2.0.0-SNAPSHOT.jar",
          "url": "runtime-js-2.0.0-SNAPSHOT.jar",
          "size": 85005,
          "sha512": "7017d377892c3b04cc9175adbda39ac7f690aa2ce4e3f13e6a26fbb037b5c73d9c75adba062d8cbcba14ee37523067a053948fc57af59f11462cd27d4c49a366",
          "sha256": "7e912ae25d99e15e52a12d05307184b66807c9a55a8ca624dbfcddffda0f53a8",
          "sha1": "3509effbd75d7ec1e7f8b5f3248258822b60ae13",
          "md5": "e6e6309230b2bb35bf8dba3594968da2"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-jsir-2.0.0-SNAPSHOT.klib",
          "url": "runtime-js-2.0.0-SNAPSHOT.klib",
          "size": 49562,
          "sha512": "ce7d20f0d7d52203b0ae81c02197792a3e30d6df934286a48769460619ce6c4a0c30753a94f96154768841bc9e6d6032df6af6331acb00cd1971e6c6c66028eb",
          "sha256": "dff3bd50ac627de50bbfad61d771dac3bcdd59ea130e7eaa24b249e48d03b01c",
          "sha1": "958407659f1039a3d39d98039f73bd75eaf352e1",
          "md5": "d0c94744d1d3c5e0d6a3fe8fa7020a2e"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-jsir-2.0.0-SNAPSHOT.klib",
          "url": "runtime-js-2.0.0-SNAPSHOT.klib",
          "size": 49562,
          "sha512": "ce7d20f0d7d52203b0ae81c02197792a3e30d6df934286a48769460619ce6c4a0c30753a94f96154768841bc9e6d6032df6af6331acb00cd1971e6c6c66028eb",
          "sha256": "dff3bd50ac627de50bbfad61d771dac3bcdd59ea130e7eaa24b249e48d03b01c",
          "sha1": "958407659f1039a3d39d98039f73bd75eaf352e1",
          "md5": "d0c94744d1d3c5e0d6a3fe8fa7020a2e"
        }
      ]
    }
  ]
}
