{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/2.0.0-SNAPSHOT/runtime-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "runtime",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-macosx64-2.0.0-SNAPSHOT.klib",
          "size": 49422,
          "sha512": "2d6bb6e35982e04999c095d46095d65c0bcce0f376d4ee92b3f63cb1350952fbd76a5ebff649fad8ec68d9488577c0822b884fc1fbcd1410969b857b21e287b6",
          "sha256": "55f67fe2cfde051746039f39e5eb2a24472fd6c3705598afe5792b1259ae7978",
          "sha1": "c822bcfb22edb5fbbf22c5b0822ebd2dd658fe24",
          "md5": "579bb9c03094e0f86ccef7fbed50ac55"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-macosx64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "runtime-macosx64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "4aa94642e3cba1e66b7cbc18b6b7344098c3ca490e136862ae862c33bce95011ea973bb66b1e7e721c94bf96119becfb4015c2998e7a50b16ecd5449866d2c36",
          "sha256": "11f7ab54c5c17b3a210de41974f185ffd5e191cf62605d8274e2add16d76de24",
          "sha1": "2042d80839dd33f0fd8ab47dccd41e65791d4289",
          "md5": "cefacb1140d010d4fa0fa116d8d5b23a"
        }
      ]
    }
  ]
}
