{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/2.0.0-SNAPSHOT/runtime-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "runtime",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-mingwx64-2.0.0-SNAPSHOT.klib",
          "size": 49344,
          "sha512": "b8432d656b9e54a3001833c50cb85c4f1796df50e686ec1ba9c12d0d370610a92652a76ed3c36aea86b4986ecec4b22388f978b0e22949b8ffd7fd5d39455575",
          "sha256": "3ff7565e0517429ba7f7065fec2c2ec181078560ede7c7bed9ebcc8263d88fe2",
          "sha1": "e8908dc940db3bf1459ea85cd84b55f8a9a40266",
          "md5": "04655ee3036c4d2fc09c49d05a4c9438"
        }
      ]
    }
  ]
}
