{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/2.0.0-SNAPSHOT/runtime-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "runtime",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-watchosarm64-2.0.0-SNAPSHOT.klib",
          "size": 49409,
          "sha512": "ccf012371ac805c7bb983cf120466637d9b46dfe5f6ff21c492e6e7e44f79b628b9d2956db6fda3b660b0078f87f61bcf60660c14f554c3b466e84c72f3a9627",
          "sha256": "56e35aa9fe30f17871d2754c3c1ce4f5bf4a61c5efcd633c7a6dc0254513b45d",
          "sha1": "ee606113ee3fd4b39562f16f36b50674ed18e69e",
          "md5": "c2bb48d87720217b0067450594cad57e"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-watchosarm64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "runtime-watchosarm64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "80cf3818f579d8a29ec94b0ac16d57f62806c637ec807eca3bf193ca56022a8d564587349e2673bee816df6d1a1166120a5d58350c634c69fe6c1e11dc8f8360",
          "sha256": "632bd35eb6fd6a3b589c798771a0dc45f4bd38f660e83579fb9e875c791d8e0f",
          "sha1": "880a69dbe05179b886c83dfced2ce9332b928152",
          "md5": "5099f4cad82a4a40bfce693171388cd4"
        }
      ]
    }
  ]
}
