{
  "formatVersion": "1.1",
  "component": {
    "url": "../../native-driver/2.0.0-SNAPSHOT/native-driver-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "native-driver",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "sqliter-driver",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-driver.klib",
          "url": "native-driver-watchosx86-2.0.0-SNAPSHOT.klib",
          "size": 46709,
          "sha512": "cbfe2eda06311cfa56348f34a04de4baea9c3a352c4c5112bfebb8eb216dbb6819d577cc9ee0866779a84b508b60fac244acf98291f33b25163f211a852075cb",
          "sha256": "58265ac863bb044c6f83383303036158b9f3433a395460686b4586965458da48",
          "sha1": "e8ee3f917947a3563e33cba7b42b12cd2cffdcfb",
          "md5": "2c063f408b788079d77fcf6bc6916242"
        }
      ]
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "sqliter-driver",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-driver-watchosx86-2.0.0-SNAPSHOT-metadata.jar",
          "url": "native-driver-watchosx86-2.0.0-SNAPSHOT-metadata.jar",
          "size": 6008,
          "sha512": "7a718d1b60fe0c0aa401b3f1097c9c5c163ebfde383ad8f7a7967687f314eb1706a6515c0ffc7834d4373bac20b649824fc39a5f0f9839e7033bc20e03cec0e1",
          "sha256": "657244b408cdfb3e8b6e537c8f534e5ec1cf364d260d44df0ac6a7a97a2d9526",
          "sha1": "a4e37ba65d41ac30c577362daf4ceb87b82fef30",
          "md5": "06704123a0ecc88e23f7c317f3632bde"
        }
      ]
    }
  ]
}
