{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "gradle-plugin",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.alecstrong.sql.psi",
          "module": "core",
          "version": {
            "requires": "0.5.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-2.0.0-SNAPSHOT.jar",
          "url": "gradle-plugin-2.0.0-SNAPSHOT.jar",
          "size": 19016747,
          "sha512": "65b1eec397228649d5149d04f7ff6bac136bf57db7a80660c994fc7f0ccef7581dfd91291b0fffac6659de11df9550685984814861dbeead2a21070e384ed991",
          "sha256": "bba8f2bebc3b860be046da2d1fbc6ea21420e267f3c1abe3f4139f86b97ad8e7",
          "sha1": "bbbe87824563e184a72fd54b0a7de72c96901c5d",
          "md5": "5238f4b4f3f18f5f0bca63bd9c9d6952"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.39.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.danielbechler",
          "module": "java-object-diff",
          "version": {
            "requires": "0.95"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "us.fatehi",
          "module": "schemacrawler-tools",
          "version": {
            "requires": "16.17.4"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "us.fatehi",
          "module": "schemacrawler-sqlite",
          "version": {
            "requires": "16.17.4"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.alecstrong.sql.psi",
          "module": "core",
          "version": {
            "requires": "0.5.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "gradle-plugin-2.0.0-SNAPSHOT.jar",
          "url": "gradle-plugin-2.0.0-SNAPSHOT.jar",
          "size": 19016747,
          "sha512": "65b1eec397228649d5149d04f7ff6bac136bf57db7a80660c994fc7f0ccef7581dfd91291b0fffac6659de11df9550685984814861dbeead2a21070e384ed991",
          "sha256": "bba8f2bebc3b860be046da2d1fbc6ea21420e267f3c1abe3f4139f86b97ad8e7",
          "sha1": "bbbe87824563e184a72fd54b0a7de72c96901c5d",
          "md5": "5238f4b4f3f18f5f0bca63bd9c9d6952"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-plugin-2.0.0-SNAPSHOT.jar",
          "url": "gradle-plugin-2.0.0-SNAPSHOT.jar",
          "size": 19016747,
          "sha512": "65b1eec397228649d5149d04f7ff6bac136bf57db7a80660c994fc7f0ccef7581dfd91291b0fffac6659de11df9550685984814861dbeead2a21070e384ed991",
          "sha256": "bba8f2bebc3b860be046da2d1fbc6ea21420e267f3c1abe3f4139f86b97ad8e7",
          "sha1": "bbbe87824563e184a72fd54b0a7de72c96901c5d",
          "md5": "5238f4b4f3f18f5f0bca63bd9c9d6952"
        }
      ]
    }
  ]
}
