{
  "formatVersion": "1.1",
  "component": {
    "url": "../../primitive-adapters/2.0.0-SNAPSHOT/primitive-adapters-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "primitive-adapters",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqldelight-primitive-adapters-jvm-2.0.0-SNAPSHOT.jar",
          "url": "primitive-adapters-jvm-2.0.0-SNAPSHOT.jar",
          "size": 4255,
          "sha512": "832c9e793bc63317147b62ec33df30d40a21f03141c54563a37ae678af49f9a97948c21385e568968af16abee1951e2a236069cfee9101929135c72a0d8f53af",
          "sha256": "ce2adad7e0370b8a359ab93dc2d155020b4223188aeec2a723a673d236af5b7f",
          "sha1": "091d4f535e24fcd0e0d9966d2a4e39556e2ea229",
          "md5": "2b189063196c40a9dc069e69b4ceb004"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqldelight-primitive-adapters-jvm-2.0.0-SNAPSHOT.jar",
          "url": "primitive-adapters-jvm-2.0.0-SNAPSHOT.jar",
          "size": 4255,
          "sha512": "832c9e793bc63317147b62ec33df30d40a21f03141c54563a37ae678af49f9a97948c21385e568968af16abee1951e2a236069cfee9101929135c72a0d8f53af",
          "sha256": "ce2adad7e0370b8a359ab93dc2d155020b4223188aeec2a723a673d236af5b7f",
          "sha1": "091d4f535e24fcd0e0d9966d2a4e39556e2ea229",
          "md5": "2b189063196c40a9dc069e69b4ceb004"
        }
      ]
    }
  ]
}
