{
  "formatVersion": "1.1",
  "component": {
    "url": "../../native-driver/2.0.0-SNAPSHOT/native-driver-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "native-driver",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "sqliter-driver",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-driver.klib",
          "url": "native-driver-tvosarm64-2.0.0-SNAPSHOT.klib",
          "size": 46700,
          "sha512": "c99da91fb6ecaef2a444df3a50cc4d5aaaaf78c70364d62b5cc4017c3808508181e58ef53ccf9ec9477c092438cf0eb3476bf3f80bf4ae02bbfe43ffa08d1d05",
          "sha256": "ca46a16fcbfb0c5ff9c8b4c7fb5c22c8cd3239eeb80a480e12c3f1c6bd873d51",
          "sha1": "a6892e763016b137c1e2a3088d579d05d39fc99b",
          "md5": "f5cb3b9f64ca947497795d3c7d4dd6d3"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "sqliter-driver",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "native-driver-tvosarm64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "native-driver-tvosarm64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 6008,
          "sha512": "44d8a6db1c47a898ccd93bc7b1c57e2475ad712ba066f6a45473a545688e57b59cc57a15db77fe8bebcceb0d688a70f0b5b7d084467d83d3d77c6f0ef1bbcb13",
          "sha256": "5a26ccb18911eaeea2e882bdafd311a0d876c2ebbccd2be5b8f6645592a51e30",
          "sha1": "e4d2952ebbc2a93a01d917dcebec169bcce2a811",
          "md5": "a06c59090b8ddcb8bb19958ced2f312e"
        }
      ]
    }
  ]
}
