{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "android-driver",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime-jvm",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "android-driver-2.0.0-SNAPSHOT.aar",
          "url": "android-driver-2.0.0-SNAPSHOT.aar",
          "size": 28082,
          "sha512": "a01d77dfd8abd77fc9dd0276857a316b519811baac0c1e61afda99f221fc56fdcae1ad5236f55431dda35e3d52d6d670d5dc841b155c158bab54b20ff7f147f6",
          "sha256": "61b308e2ba5ee61fb80a07c775c8eccd766836270f5daef481b3833285842483",
          "sha1": "124637239607ca4656ff6cd5dd9d482b7a682969",
          "md5": "8546d6c4898efa31fdac206258a60ee2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime-jvm",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "android-driver-2.0.0-SNAPSHOT.aar",
          "url": "android-driver-2.0.0-SNAPSHOT.aar",
          "size": 28082,
          "sha512": "a01d77dfd8abd77fc9dd0276857a316b519811baac0c1e61afda99f221fc56fdcae1ad5236f55431dda35e3d52d6d670d5dc841b155c158bab54b20ff7f147f6",
          "sha256": "61b308e2ba5ee61fb80a07c775c8eccd766836270f5daef481b3833285842483",
          "sha1": "124637239607ca4656ff6cd5dd9d482b7a682969",
          "md5": "8546d6c4898efa31fdac206258a60ee2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-driver-2.0.0-SNAPSHOT-sources.jar",
          "url": "android-driver-2.0.0-SNAPSHOT-sources.jar",
          "size": 3483,
          "sha512": "b9eb1555cf687bc40c992d3e73acc860ea6c3cd925022e0e468356357be5e53a0afe7ac2c5010dc47a9db29a6e16941051fc80ee4376956cb9067347cbf3bacb",
          "sha256": "db6c37d1a2cd9acbc9410f9eae84a85eea7f664b674c60e5b93ca751d169e59a",
          "sha1": "544ee42586a6c0b23221b7eadcbdc7bb44a86ce2",
          "md5": "2c80d6e25dc5809fd6df2c2e50723898"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-driver-2.0.0-SNAPSHOT-javadoc.jar",
          "url": "android-driver-2.0.0-SNAPSHOT-javadoc.jar",
          "size": 276253,
          "sha512": "7164834dde533bc12a5e9f5997bb54ba6906019ddf276d608a9c019fa938d9cc6c0920f0dc61962f9d5a46073145fe4e7bb73addfbee17ecd2820ff32fdd64dd",
          "sha256": "7345f968def38fee641973af2b66402b986af1f042d2dcd818f7147ae1774be8",
          "sha1": "5f7dd30a412dff4b51bbd636294ef53d2cfc9057",
          "md5": "d48496e6634eacc96ef5e4b47ed8b6cd"
        }
      ]
    }
  ]
}
