{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "rxjava2-extensions",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "rxjava2-extensions-2.0.0-SNAPSHOT.jar",
          "url": "rxjava2-extensions-2.0.0-SNAPSHOT.jar",
          "size": 5901,
          "sha512": "2381a58254de4846a800dd73619132e94f4aeae651e00a9394421fc63032596df5d5b9ef37f5b1a274631eea2c88a3afec8124c22918108376d4164efd41df58",
          "sha256": "aef3e148ea6adec133a589f0bdf655a59c833c38d2a92ffe46cf7488aad71d39",
          "sha1": "cff2e96a7750b39251114f0c6f6dd840640688a2",
          "md5": "ab2035f3a25b7fac0e6eabf046a3fcbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "rxjava2-extensions-2.0.0-SNAPSHOT.jar",
          "url": "rxjava2-extensions-2.0.0-SNAPSHOT.jar",
          "size": 5901,
          "sha512": "2381a58254de4846a800dd73619132e94f4aeae651e00a9394421fc63032596df5d5b9ef37f5b1a274631eea2c88a3afec8124c22918108376d4164efd41df58",
          "sha256": "aef3e148ea6adec133a589f0bdf655a59c833c38d2a92ffe46cf7488aad71d39",
          "sha1": "cff2e96a7750b39251114f0c6f6dd840640688a2",
          "md5": "ab2035f3a25b7fac0e6eabf046a3fcbe"
        }
      ]
    }
  ]
}
