{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "sqlite-driver",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "jdbc-driver",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-driver-2.0.0-SNAPSHOT.jar",
          "url": "sqlite-driver-2.0.0-SNAPSHOT.jar",
          "size": 10786,
          "sha512": "3dad1e7cf9ee6a305d082c15ebeec8444367cd53e4495a5bdc42b10fb08fbb9047fa682a3f012f2326f6a76c08f3393592b23a9007d2c739e32879acf341ae7e",
          "sha256": "b6ec273d9a84549ba14fcf20eeed8846849a108d21adce51245af0a75bc55b10",
          "sha1": "3956839fbb0946587b32597878f7c938697d47b7",
          "md5": "a3284a3b3ec5a95b5428f115a4a18460"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.xerial",
          "module": "sqlite-jdbc",
          "version": {
            "requires": "3.39.2.0"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "jdbc-driver",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-driver-2.0.0-SNAPSHOT.jar",
          "url": "sqlite-driver-2.0.0-SNAPSHOT.jar",
          "size": 10786,
          "sha512": "3dad1e7cf9ee6a305d082c15ebeec8444367cd53e4495a5bdc42b10fb08fbb9047fa682a3f012f2326f6a76c08f3393592b23a9007d2c739e32879acf341ae7e",
          "sha256": "b6ec273d9a84549ba14fcf20eeed8846849a108d21adce51245af0a75bc55b10",
          "sha1": "3956839fbb0946587b32597878f7c938697d47b7",
          "md5": "a3284a3b3ec5a95b5428f115a4a18460"
        }
      ]
    }
  ]
}
