{
  "formatVersion": "1.1",
  "component": {
    "url": "../../async-extensions/2.0.0-SNAPSHOT/async-extensions-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "async-extensions",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "async-extensions.klib",
          "url": "async-extensions-iosarm32-2.0.0-SNAPSHOT.klib",
          "size": 10132,
          "sha512": "393f23f5b94c86a63ab1de2b87db52cc666d47c3a257d5b5fd094dc012826a7c54fb62f4ab5c059335f7d4c2244dd3d3a42291bc6b4e634ee5f5972c47432a79",
          "sha256": "9c0854dfe8a6f6740071bac8362b2e3d49cf12267500f56d03d21323df8ad108",
          "sha1": "5cbbe9274538897d8319db79495c00c2401fae7d",
          "md5": "7af3b7ec728b136a824c12e4d556c578"
        }
      ]
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqldelight-async-extensions-iosarm32-2.0.0-SNAPSHOT-metadata.jar",
          "url": "async-extensions-iosarm32-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "35160bc5e87926fd4d66b761e6e1736d395de8b04c9f76184a897059bd092897ce351367ae7fd0e664712e1028a4518a897d6febb4982b35cb1bfab2b9fc3ef4",
          "sha256": "f1b7ee81c8b8ee6a244d3ce8201c7d3c98d58eded5f68f90a38051d69f915757",
          "sha1": "405d68dfeb041f63dd6ff0adfe0c9f7972d70007",
          "md5": "d6f6c32e2c64f0d5cf7d241e5fa26c9a"
        }
      ]
    }
  ]
}
