{
  "formatVersion": "1.1",
  "component": {
    "url": "../../primitive-adapters/2.0.0-SNAPSHOT/primitive-adapters-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "primitive-adapters",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "primitive-adapters.klib",
          "url": "primitive-adapters-watchosarm32-2.0.0-SNAPSHOT.klib",
          "size": 7445,
          "sha512": "e4532c94743f14549ce9a235d6a57253f1c4b70746853149318b06afd80b1b448fd9a9ae879c10a0878418869df45debf75529422f6f0a6a4c5b0beee7c17857",
          "sha256": "0d8a89cf47a8f584457a26cdd19e7ad4490c57b4dbaca05622d9b5d5d3bfc0cb",
          "sha1": "6ab1d3847a3b0cb6512a93e995fddc7dbcbf83b2",
          "md5": "c944c1723673e7487da6785a1206d0cc"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqldelight-primitive-adapters-watchosarm32-2.0.0-SNAPSHOT-metadata.jar",
          "url": "primitive-adapters-watchosarm32-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e98abd2c104bbfd10b3cb3c7545993db72cb5928ba8db8a73e78a09fd3a58c73bbb0ec2985804435c4a3a2e3dcab6dadb60a27257bfa8ef4ecf036446a48bac7",
          "sha256": "0ffd964b4aee7d7e2ee7777ee6e353f616514207055ca5a14f7e9e749c88f3d8",
          "sha1": "b7ccbb9abd5905bff6f27717e41f358354fbb972",
          "md5": "7e47fb3a9b42930b21a6a8dd4c21ed05"
        }
      ]
    }
  ]
}
