{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "sqlite-json-module",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-json-module-2.0.0-SNAPSHOT.jar",
          "url": "sqlite-json-module-2.0.0-SNAPSHOT.jar",
          "size": 30467,
          "sha512": "b081213c67f855c3adcf5ab1503cb8e3eb4b43c83f58d14db54c10d3a52b14bd2dfa6f8d2f3dfd2bf963c20c07125630c446bfbff0839b5fceffe21f83bd6bc6",
          "sha256": "31402e545e506a65a38dc64aa2296036050859d7899c3d4514b9d63a6e32de58",
          "sha1": "6436790d4dfb76514906fb8abb6eaa0b0320b7f5",
          "md5": "0be6dd502c6a92d5f476087258764b62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqlite-json-module-2.0.0-SNAPSHOT.jar",
          "url": "sqlite-json-module-2.0.0-SNAPSHOT.jar",
          "size": 30467,
          "sha512": "b081213c67f855c3adcf5ab1503cb8e3eb4b43c83f58d14db54c10d3a52b14bd2dfa6f8d2f3dfd2bf963c20c07125630c446bfbff0839b5fceffe21f83bd6bc6",
          "sha256": "31402e545e506a65a38dc64aa2296036050859d7899c3d4514b9d63a6e32de58",
          "sha1": "6436790d4dfb76514906fb8abb6eaa0b0320b7f5",
          "md5": "0be6dd502c6a92d5f476087258764b62"
        }
      ]
    }
  ]
}
