{
  "formatVersion": "1.1",
  "component": {
    "group": "app.cash.sqldelight",
    "module": "jdbc-driver",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "jdbc-driver-2.0.0-SNAPSHOT.jar",
          "url": "jdbc-driver-2.0.0-SNAPSHOT.jar",
          "size": 24012,
          "sha512": "b6dbb0dac86c205e42e02376958f51411b28f3e4538c056750074abd3c832a94eef2eab70dbe02e26f10c46978b94c798f1736ac654a83b958462974f5686de2",
          "sha256": "1df260b2cfe65c6853a0e15e520c8e5f5d27a393bd996e80c6fbbefcc61100a4",
          "sha1": "b673d12bac9698d87ef6786a19c2aaa229b06d66",
          "md5": "b25b4a7bf665125de815e435c70d2eed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "jdbc-driver-2.0.0-SNAPSHOT.jar",
          "url": "jdbc-driver-2.0.0-SNAPSHOT.jar",
          "size": 24012,
          "sha512": "b6dbb0dac86c205e42e02376958f51411b28f3e4538c056750074abd3c832a94eef2eab70dbe02e26f10c46978b94c798f1736ac654a83b958462974f5686de2",
          "sha256": "1df260b2cfe65c6853a0e15e520c8e5f5d27a393bd996e80c6fbbefcc61100a4",
          "sha1": "b673d12bac9698d87ef6786a19c2aaa229b06d66",
          "md5": "b25b4a7bf665125de815e435c70d2eed"
        }
      ]
    }
  ]
}
