{
  "formatVersion": "1.1",
  "component": {
    "url": "../../primitive-adapters/2.0.0-SNAPSHOT/primitive-adapters-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "primitive-adapters",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "primitive-adapters.klib",
          "url": "primitive-adapters-tvosx64-2.0.0-SNAPSHOT.klib",
          "size": 7402,
          "sha512": "c2c32e0d690421c434398fb0b4c314f993aa550948704ee9e458a49729a7e8cc6fc2b482538dfb4da41c00a569f7772ac904094cdb13d9b3339e140aea3881b1",
          "sha256": "b7b47bc0df756ed0fe54011ca3552e33a44be9da59966be612f8b9e58a709e66",
          "sha1": "4097af2865623ddb9fbf4ca8ceada769aae27420",
          "md5": "7646890474a33d92293c0fb71b15977c"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "app.cash.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "2.0.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "sqldelight-primitive-adapters-tvosx64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "primitive-adapters-tvosx64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "e98abd2c104bbfd10b3cb3c7545993db72cb5928ba8db8a73e78a09fd3a58c73bbb0ec2985804435c4a3a2e3dcab6dadb60a27257bfa8ef4ecf036446a48bac7",
          "sha256": "0ffd964b4aee7d7e2ee7777ee6e353f616514207055ca5a14f7e9e749c88f3d8",
          "sha1": "b7ccbb9abd5905bff6f27717e41f358354fbb972",
          "md5": "7e47fb3a9b42930b21a6a8dd4c21ed05"
        }
      ]
    }
  ]
}
