{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime/2.0.0-SNAPSHOT/runtime-2.0.0-SNAPSHOT.module",
    "group": "app.cash.sqldelight",
    "module": "runtime",
    "version": "2.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime.klib",
          "url": "runtime-macosarm64-2.0.0-SNAPSHOT.klib",
          "size": 49438,
          "sha512": "001c7d52a7323c6e24c2a632ecebc53996297381f2dd0a33420e329b8b46be50a9d8014db913c182728ca1310cf5fd1f66d47ad0a4191e3614f23d79fc00867b",
          "sha256": "9d92f1c760215de4ec3cdb5eeed1c5a200d259f3b4b12cd7de45f16b3e0eeb78",
          "sha1": "310f454e70ee5c5370b7e726c0f401fd859bdf9a",
          "md5": "e91cb0a62563fc62b2ebc114b9123b38"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrency",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "com.jetbrains.rd",
              "module": "*"
            },
            {
              "group": "com.github.jetbrains",
              "module": "jetCheck"
            },
            {
              "group": "org.roaringbitmap",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "runtime-macosarm64-2.0.0-SNAPSHOT-metadata.jar",
          "url": "runtime-macosarm64-2.0.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "5459f850b7a1d8faa2a060a54e58e0f9b8a95ee4707249fa5ac91ebc1ab53dea5f4cf99d00b55504cad06b691eb93298a7f856f894ebbf065ef716cf203ed572",
          "sha256": "df5a9a56e56d5ae198839746da27922b57e8ad139cc10dc8387902dd5c2571a4",
          "sha1": "e5a999e13861341b2edc3e3ff125f5d31459aa6f",
          "md5": "5153009af1fdc32b86ea7b5918bdfa5e"
        }
      ]
    }
  ]
}
