name: Release

on:
  release:
    types: [ created ]

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  publishMavenCentral:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    environment: CD

    steps:
      - name: Set environment for version
        uses: hfhbd/actions/setup-version@main
        id: version
      - uses: actions/checkout@v5
      - uses: gradle/actions/setup-gradle@v4

      - name: Release maven artifacts
        run: ./gradlew publishToMavenCentral -Pversion=${{ steps.version.outputs.version }}
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PASSWORD }}
